services:
  postgres:
    image: postgres:16-alpine
    container_name: agro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agroforestry
    ports:
      - '5433:5432'
    volumes:
      - agro-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d agroforestry']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  agro-pgdata:
